// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: greeter.proto

package example.greeter;

public interface HelloResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:example.greeter.HelloResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string text = 1;</code>
   * @return The text.
   */
  java.lang.String getText();
  /**
   * <code>string text = 1;</code>
   * @return The bytes for text.
   */
  com.google.protobuf.ByteString
      getTextBytes();
}
